# Generated by Django 5.0.4 on 2024-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
