# Generated by Django 5.0.4 on 2024-05-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_userfollowing_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('to_user', 'from_user')},
        ),
    ]
